/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module compar (
  input A,
  input B,
  input C,
  input D,
  input E,
  input F,
  input G,
  input H,
  input I,
  input J,
  input K,
  output Y,
  output X,
  output W,
  output V,
  output U,
  output T
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  assign U = ((A & C & D & F & G & J) | (A & C & D & F & G & I) | (A & C & D & F & G & H) | (A & C & D & E) | (A & B));
  assign s0 = ~ A;
  assign s9 = ~ B;
  assign s1 = ~ C;
  assign s2 = ~ D;
  assign s10 = ~ E;
  assign s3 = ~ F;
  assign s4 = ~ G;
  assign s5 = ~ H;
  assign s8 = ~ I;
  assign s7 = ~ J;
  assign s6 = ~ K;
  assign Y = ((s0 & B & s1 & s2 & s3 & s4 & s5 & s6) | (s0 & B & s1 & s2 & s3 & s4 & s5 & s7) | (s0 & B & s1 & s2 & s3 & s4 & s5 & s8) | (s0 & s9 & C & F & I) | (s0 & s9 & C & F & H) | (s0 & s9 & C & F & G) | (s0 & B & s1 & s2 & s10) | (s0 & s9 & C & E) | (s0 & s9 & C & D));
  assign X = ((s0 & B & s2 & E & s4 & s5 & I & J & K) | (s0 & B & s2 & E & s4 & H & s8 & s6) | (s0 & B & s2 & E & s4 & H & s8 & s7) | (s0 & B & C & s2 & s4 & s5) | (s0 & B & s2 & E & s3 & H) | (s0 & B & s2 & E & s3 & G) | (s0 & B & s1 & E & F) | (s0 & B & C & s2 & s10) | (s0 & B & s1 & D));
  assign W = ((s0 & B & C & E & F & H & J & K) | (A & s9 & s1 & s10 & s3 & s4 & s7) | (s0 & B & C & E & F & H & I) | (A & s9 & s1 & s10 & s3 & s4 & s8) | (A & s9 & s1 & s10 & s3 & s4 & s5) | (s0 & B & C & E & F & G) | (s0 & B & C & D) | (A & s9 & s1 & s2));
  assign V = ((A & s9 & D & s10 & s4 & H & I & J) | (A & s9 & D & s10 & G & s5 & s8 & s7) | (A & s9 & D & s10 & F & s4) | (A & s9 & s1 & D & G) | (A & s9 & C & s10 & s3) | (A & s9 & s1 & D & E) | (A & s9 & C & s2));
  assign T = ((s0 & s9 & s2 & s10 & s4 & s5 & s8 & K) | (s0 & s9 & s2 & s10 & s4 & s5 & s8 & J) | (s0 & s9 & s2 & s10 & F & s4 & s5 & s8) | (s0 & s9 & C & s2 & s10 & s3) | (s0 & s9 & s1 & I) | (s0 & s9 & s1 & H) | (s0 & s9 & s1 & G) | (s0 & s9 & s1 & E) | (s0 & s9 & s1 & D));
endmodule
