/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module mo (
  input Clo, A1, Echo,
  output S, S2, A_1, B_1, C_1, D_1, E_1, F_1
);

  wire op_to_clr;
  wire op_to_clr1;
  wire s1_to_mux;
  wire s2_to_mux;
  wire s3_to_mux;
  wire s4_to_mux;
  wire s5_to_mux;
  wire s6_to_mux;
  wire s7_to_mux;
  wire A;
  wire B;
  wire C;
  wire Echo_Inf;


pulso pulso1(op_to_clr, Clo, s1_to_mux);
pulso2 pulso21(op_to_clr, Clo, s2_to_mux);
pulso3 pulso31(op_to_clr, Clo, s3_to_mux);
pulso4 pulso41(op_to_clr, Clo, s4_to_mux);
pulso5 pulso51(op_to_clr, Clo, s5_to_mux);
pulso6 pulso61(op_to_clr, Clo, s6_to_mux);
pulso7 pulso71(op_to_clr, Clo, s7_to_mux);

clock_divider clock_divider1(Clo, op_to_clr);
clock_divider2 clock_divider21(Clo, op_to_clr1);
multi multi1( A, B, C, s1_to_mux, s2_to_mux, s3_to_mux, s4_to_mux, s5_to_mux, s6_to_mux, s7_to_mux,S);
contador contador1( op_to_clr1, , A, B, C);

Nivel Nivel1(Clo, Echo_Inf, S2, A_1, B_1, C_1, D_1, E_1, F_1);

assign Echo_Inf = ~A1 & Echo;

endmodule
